#!/usr/bin/env bash

echo "Building ironruby (debug version)"
rake compile:all configuration=debug
echo "Building ironruby (release version)"
rake compile:all configuration=release
echo "Done building."

